<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if($customerSession->isLoggedIn()) : ?>
    <div class="header_search_img">
        <a href="#"><img src="<?php echo $block->getViewFileUrl('images/search.png'); ?>"/></a>
    </div>
    <div class="header_link_logout">
		<a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/logout");?>"><?php echo __('Logout')?></a>
	</div>
<?php else: ?>
<div class="header_search_img">
        <a href="#"><img src="<?php echo $block->getViewFileUrl('images/search.png'); ?>"/></a>
    </div>
    <div class="header_link_login">
		<a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/login");?>"><img src="<?php echo $block->getViewFileUrl('images/avatar.png'); ?>"/></a>
	</div>
<?php endif;?>

<script>
    require(
        [
            'jquery',
        ],
        function($) {
            $('.header_search_img').on('click',
                function(event) {
                    event.stopPropagation();
                    $('.block-search').toggleClass('active');
                });
            $(".page-main").click(function() {
                console.log('test')
                $(".block-search").removeClass("active");
            });
        });
</script>
<script type="text/javascript">
    console.log('the first way');
</script>
<script type="text/javascript">
    require( [
            'jquery'
        ],
        function($) {
            console.log('Imperative way');
        });
</script>

