<a href="#" class="left">LEFT</a> | <a href="#" class="right">RIGHT</a> | <a href="#" class="top">TOP</a> | <a href="#" class="bottom">BOTTOM</a> | <a href="#" class="go">GO</a>
<br /><br />
<div id="little-box" style="background-color:black; position: relative; width:10px; height:10px;"></div>

<script>
    require(
        [
            'jquery',
        ],
        function($) {
            $('.right').click(function (e) {
                e.preventDefault();
                $("#little-box").animate({
                    left: "+=30"
                });
            });
            $('.left').click(function (e) {
                e.preventDefault();
                $("#little-box").animate({
                    left: "-=30"
                });
            });
            $('.top').click(function (e) {
                e.preventDefault();
                $("#little-box").animate({
                    top: "-=30"
                });
            });
            $('.bottom').click(function (e) {
                e.preventDefault();
                $("#little-box").animate({
                    top: "+=30"
                });
            });
        });
</script>



<script type="text/javascript">
    require(
        [
            'jquery',
        ],
        function($) {

            $(".go").click(function (e) {
                e.preventDefault();
                $("#little-box").animate({opacity: "0.1", left: "+=400"}, 1200)
                    .animate({opacity: "0.4", top: "+=160", height: "20", width: "20"}, "slow")
                    .animate({opacity: "1", left: "0", height: "100", width: "100"}, "slow")
                    .animate({top: "0", height: "10", width: "10"}, "fast")
                    .slideUp()
                    .slideDown("slow");
            });
        });
</script>
