<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$id = $this->getRequest()->getParam('id');
$_product = $this->getProduct($id);
$name = $_product->getName();
/*$productPriceById = $_product->getPrice();*/
$imageUrl = $_product->getImageUrl();
?>

<div class="product_test" data-mage-init='{"Magento_Catalog/js/test":{}}'>
    <?= $block->getChildHtml('gallery.test'); ?>
    <?php echo $imageUrl ?>
    <div class="product_info_test">
        <?php echo $name ?>
        <?= $block->getChildHtml('price'); ?></div>
      <div class="fixed_buy_test">
          <div class="wishlist_test"><?= $block->getChildHtml('wishlist'); ?></div>
          <div class="compare_test"><?= $block->getChildHtml('compare'); ?></div>
          <div class="minicart_test"><?= $block->getChildHtml('minicart.test'); ?></div>
      </div>
    </div>




