<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<div class="title_test"><span class="mg_title"><?php
echo "microgreen";
?></span>
<span class="mg_undertitle"><?php
    echo "New trend of healthy food";
    ?></span>
<span class="undertitle_two"><?php
    echo "Order the samplers for free right now";
    ?></span>
<button>Order</button></div>
